#!/bin/bash
TOMCAT_HOME="/opt/tomcat"
START_SCRIPT="$TOMCAT_HOME/startup.sh"
export TOMCAT_USER=tomcat

#tomcat_USAGE is the message if this script is called without any options
#tomcat_USAGE="Usage: $0 {\e[00;32mstart\e[00m|\e[00;31mstop\e[00m|\e[00;31mkill\e[00m|\e[00;32mstatus\e[00m|\e[00;31mrestart\e[00m}"

#SHUTDOWN_WAIT is wait time in seconds for java proccess to stop
SHUTDOWN_WAIT=20

tomcat_pid() {
                        echo `pgrep -f 'com.centra.tomcat.embed.EmbeddedTomcat'`
                }

start() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo -e "\e[00;31mtomcat is already running (pid: $pid)\e[00m"
  else
    # Start tomcat
    echo -e "\e[00;32mStarting tomcat Server\e[00m"
        myid=`id -nu`
            if [ "$myid" = "$TOMCAT_USER" ];then
              cd $TOMCAT_HOME
               ./startup.sh
        else
                echo -e "\e[00;31mtomcat user $TOMCAT_USER does not exists. Starting with $(id)\e[00m"
                cd $TOMCAT_HOME
				./startup.sh
        fi
        status
  fi
  return 0
}

status(){
          pid=$(tomcat_pid)
          if [ -n "$pid" ]
            then echo -e "\e[00;32mtomcat is running with pid: $pid\e[00m"
          else
            echo -e "\e[00;31mtomcat is not running\e[00m"
            return 3
          fi
}

terminate() {
        echo -e "\e[00;31mTerminating Tomcat\e[00m"
        kill -9 $(tomcat_pid)
}

stop() {
  pid=$(tomcat_pid)
  if [ -n "$pid" ]
  then
    echo -e "\e[00;31mStoping Tomcat\e[00m"
        #kill -9 $pid
        terminate
        echo "tomcat killed with PID $pid"
    let kwait=$SHUTDOWN_WAIT
    count=0;
    until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -gt $kwait ]
    do
      echo -n -e "\n\e[00;31mwaiting for processes to exit\e[00m";
      sleep 1
      let count=$count+1;
    done

    if [ $count -gt $kwait ]; then
      echo -n -e "\n\e[00;31mkilling processes didn't stop after $SHUTDOWN_WAIT seconds\e[00m"
      terminate
    fi
  else
    echo -e "\e[00;31mTomcat is not running\e[00m"
  fi
  return 0
}


currentdate=`date '+%Y%d%m'`
expirydate=$(date -d 2017-02-25 +"%Y%m%d")    # = 20170225

#echo $currentdate
#echo $expirydate
if [ $expirydate -ge $currentdate ]; 
then
 echo 'Restarting tomcat';
        stop
        sleep 10
        start
 else
 echo 'Current date is greater than 2017-02-02';
fi

case $1 in
        start)
          start
        ;;
        stop)
          stop
        ;;
        restart)
          stop
          sleep 10
          start
        ;;
        status)
                status
                exit $?
        ;;
        kill)
                terminate
        ;;
        *)
                echo -e $tomcat_USAGE
        ;;
esac
exit 0
